document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>Document</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'./css/common.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'./css/style.css\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <!-- 头部区域 -->");
document.writeln("    <header>");
document.writeln("        <div class=\'w\'>");
document.writeln("            <div class=\'head_left\'>");
document.writeln("                <ul>");
document.writeln("                    <li><a href=\'\'>小米商城</a></li>");
document.writeln("                    <li><a href=\'\'></a></li>");
document.writeln("                    <li><a href=\'\'>MIUI</a></li>");
document.writeln("                    <li><a href=\'\'></a></li>");
document.writeln("                    <li><a href=\'\'>loT</a></li>");
document.writeln("                    <li><a href=\'\'></a></li>");
document.writeln("                    <li><a href=\'\'>云服务</a></li>");
document.writeln("                    <li><a href=\'\'></a></li>");
document.writeln("                    <li><a href=\'\'>金融</a></li>");
document.writeln("                    <li><a href=\'\'></a></li>");
document.writeln("                    <li><a href=\'\'>有品</a></li>");
document.writeln("                    <li><a href=\'\'></a></li>");
document.writeln("                    <li><a href=\'\'>小爱开放平台</a></li>");
document.writeln("                    <li><a href=\'\'></a></li>");
document.writeln("                    <li><a href=\'\'>企业团购</a></li>");
document.writeln("                    <li><a href=\'\'></a></li>");
document.writeln("                    <li><a href=\'\'>资质证照</a></li>");
document.writeln("                    <li><a href=\'\'></a></li>");
document.writeln("                    <li><a href=\'\'>协议规则</a></li>");
document.writeln("                    <li><a href=\'\'></a></li>");
document.writeln("                    <li><a href=\'\'>下载app</a></li>");
document.writeln("                    <li><a href=\'\'></a></li>");
document.writeln("                    <li><a href=\'\'>SelectLocation</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'head_right\'>");
document.writeln("                <ul>");
document.writeln("                    <li><a href=\'\'>登录</a></li>");
document.writeln("                    <li><a href=\'\'>注册</a></li>");
document.writeln("                    <li><a href=\'\'>消息通知</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'shopCar\'>");
document.writeln("                <a href=\'\' class=\'buyCar\'>");
document.writeln("                    <div class=\'car\'>");
document.writeln("                        <i class=\'iconfont icon-gouwuche\'></i>");
document.writeln("                    </div>");
document.writeln("                    购物车 (0)");
document.writeln("                </a>");
document.writeln("            </div>");
document.writeln("            <div class=\'shopCar_select\'>");
document.writeln("                <p>购物车中还没有商品,赶紧选购吧!</p>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </header>");
document.writeln("    <!-- 头部区域结束 -->");
document.writeln("    <!-- 导航区域 -->");
document.writeln("    <div class=\'w\'>");
document.writeln("        <nav>");
document.writeln("            <a href=\'#\' class=\'logo\'></a>");
document.writeln("            <div class=\'nav_head\'>");
document.writeln("                <ul>");
document.writeln("                    <li><a href=\'#\'>小米手机</a></li>");
document.writeln("                    <li><a href=\'#\'>Redmi红米</a></li>");
document.writeln("                    <li><a href=\'#\'>电视</a></li>");
document.writeln("                    <li><a href=\'#\'>笔记本</a></li>");
document.writeln("                    <li><a href=\'#\'>家电</a></li>");
document.writeln("                    <li><a href=\'#\'>路由器</a></li>");
document.writeln("                    <li><a href=\'#\'>智能硬件</a></li>");
document.writeln("                    <li><a href=\'#\'>服务</a></li>");
document.writeln("                    <li><a href=\'#\'>社区</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'search\'>");
document.writeln("                <input type=\'text\' placeholder=\'小米10\'>");
document.writeln("                <button>");
document.writeln("                    <a href=\'#\'>");
document.writeln("                        <i class=\'iconfont icon-fangdajing");
document.writeln("                    \'></i>");
document.writeln("                    </a>");
document.writeln("                </button>");
document.writeln("            </div>");
document.writeln("        </nav>");
document.writeln("    </div>");
document.writeln("    <!-- 导航区域结束 -->");
document.writeln("    <!-- 页尾区域 -->");
document.writeln("    <footer>");
document.writeln("        <div class=\'w\'>");
document.writeln("            <div class=\'safeMod\'>");
document.writeln("                <ul>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:;\'>");
document.writeln("                            <i class=\'iconfont icon-weihu\'></i>");
document.writeln("                            <span>预约维护服务</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:;\'>");
document.writeln("                            <i class=\'iconfont icon-7tianwuliyoutuihuo\'></i>");
document.writeln("                            <span>7天无理由退货</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:;\'>");
document.writeln("                            <i class=\'iconfont icon-15tianwuliyoutuihuo\'></i>");
document.writeln("                            <span>15天免费换货</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:;\'>");
document.writeln("                            <i class=\'iconfont icon-baoyou\'></i>");
document.writeln("                            <span>满99元包邮</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:;\'>");
document.writeln("                            <i class=\'iconfont icon-wangdianchaxun\'></i>");
document.writeln("                            <span>520余家售后网点</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'helpMod\'>");
document.writeln("                <div class=\'helpMod_left\'>");
document.writeln("                    <ul>");
document.writeln("                        <li>");
document.writeln("                            <dt> 帮助中心</dt>");
document.writeln("                            <a href=\'#\'>");
document.writeln("                                <dd>账户管理</dd>");
document.writeln("                                <dd>购物指南</dd>");
document.writeln("                                <dd>订单操作</dd>");
document.writeln("");
document.writeln("                            </a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <dt> 服务支持</dt>");
document.writeln("                            <a href=\'#\'>");
document.writeln("                                <dd>售后政策</dd>");
document.writeln("                                <dd>自动服务</dd>");
document.writeln("                                <dd>相关下载</dd>");
document.writeln("                            </a>");
document.writeln("");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <dt> 线下门店</dt>");
document.writeln("                            <a href=\'#\'>");
document.writeln("                                <dd>小米之家</dd>");
document.writeln("                                <dd>服务网点</dd>");
document.writeln("                                <dd>授权体验店</dd>");
document.writeln("");
document.writeln("                            </a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <dt>关于小米 </dt>");
document.writeln("                            <a href=\'#\'>");
document.writeln("                                <dd>了解小米</dd>");
document.writeln("                                <dd>加入小米</dd>");
document.writeln("                                <dd>投资者关系</dd>");
document.writeln("                                <dd>企业社会责任</dd>");
document.writeln("                            </a>");
document.writeln("");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <dt>关注我们</dt>");
document.writeln("                            <a href=\'#\'>");
document.writeln("                                <dd>新浪微博</dd>");
document.writeln("                                <dd>官方微信</dd>");
document.writeln("                                <dd>联系我们</dd>");
document.writeln("                                <dd>公益基金会</dd>");
document.writeln("                            </a>");
document.writeln("");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <dt>特色服务</dt>");
document.writeln("                            <a href=\'#\'>");
document.writeln("                                <dd>F码通道</dd>");
document.writeln("                                <dd>礼物码</dd>");
document.writeln("                                <dd>防伪查询</dd>");
document.writeln("                            </a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'helpMod_right\'>");
document.writeln("                    <div class=\'service\'>");
document.writeln("                        <h3>400-100-5678</h3>");
document.writeln("                        <p>8:00-18:00(仅收市话费)</p>");
document.writeln("                        <span>");
document.writeln("                            <i class=\'iconfont icon-kefu\'></i>");
document.writeln("                            <a href=\'#\'>人工客服</a>");
document.writeln("                        </span>");
document.writeln("                        <a href=\'#\'>");
document.writeln("                            关注小米:");
document.writeln("                            <i class=\'iconfont icon-weibo\'></i>");
document.writeln("                            <i class=\'iconfont icon-weixin\'></i>");
document.writeln("                        </a>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'footer_nav\'>");
document.writeln("                <ul>");
document.writeln("                    <li><a href=\'\'>小米商城</a></li>");
document.writeln("                    <li></li>");
document.writeln("                    <li><a href=\'\'>MIUI</a></li>");
document.writeln("                    <li></li>");
document.writeln("                    <li><a href=\'\'>米家</a></li>");
document.writeln("                    <li></li>");
document.writeln("                    <li><a href=\'\'>米聊</a></li>");
document.writeln("                    <li></li>");
document.writeln("                    <li><a href=\'\'>多看</a></li>");
document.writeln("                    <li></li>");
document.writeln("                    <li><a href=\'\'>游戏</a></li>");
document.writeln("                    <li></li>");
document.writeln("                    <li><a href=\'\'>政企服务</a></li>");
document.writeln("                    <li></li>");
document.writeln("                    <li><a href=\'\'>小米天猫店</a></li>");
document.writeln("                    <li></li>");
document.writeln("                    <li><a href=\'\'>小米集团隐私政策</a></li>");
document.writeln("                    <li></li>");
document.writeln("                    <li><a href=\'\'>小米公司儿童信息保护规则</a></li>");
document.writeln("                    <li></li>");
document.writeln("                    <li><a href=\'\'>小米商城隐私政策</a></li>");
document.writeln("                    <li></li>");
document.writeln("                    <li><a href=\'\'>小米商城用户协议</a></li>");
document.writeln("                    <li></li>");
document.writeln("                    <li><a href=\'\'>问题反馈</a></li>");
document.writeln("                    <li></li>");
document.writeln("                    <li><a href=\'\'>Select Location</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'explain\'>");
document.writeln("                <p>");
document.writeln("                    © mi.com 京ICP证110507号 京ICP备10046444号 京公网安备11010802020134号 京网文[2020]0276-042号<br>");
document.writeln("                    （京）网械平台备字（2018）第00005号 互联网药品信息服务资格证 (京)-非经营性-2014-0090 营业执照 医疗器械质量公告<br>");
document.writeln("                    增值电信业务许可证 网络食品经营备案（京）【2018】WLSPJYBAHF-12 食品经营许可证<br>");
document.writeln("                    违法和不良信息举报电话：185-0130-1238 知识产权侵权投诉 本网站所列数据，除特殊说明，所有数据均出自我司实验室测试");
document.writeln("                </p>");
document.writeln("            </div>");
document.writeln("            <div class=\'peugeot\'>");
document.writeln("                <div class=\'ac\'>");
document.writeln("                    <a href=\'#\'>");
document.writeln("                        <img src=\'./images/truste.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'eva\'>");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\'#\'><img src=\'./images/v-logo-1.png\' alt=\'\'></a></li>");
document.writeln("                        <li><a href=\'#\'><img src=\'./images/v-logo-2.png\' alt=\'\'></a></li>");
document.writeln("                        <li><a href=\'#\'><img src=\'./images/v-logo3.png\' alt=\'\'></a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("");
document.writeln("        </div>");
document.writeln("    </footer>");
document.writeln("    <!-- 页尾区域结束 -->");
document.writeln("    <!-- 侧边栏区域 -->");
document.writeln("    <div class=\'sideBar\'>");
document.writeln("        <ul>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>");
document.writeln("                    <i class=\'iconfont icon-shouji\'></i>");
document.writeln("                    <span> 手机APP</span>");
document.writeln("                </a>");
document.writeln("");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>");
document.writeln("                    <i class=\'iconfont icon-gerenzhongxin");
document.writeln("                    \'></i>");
document.writeln("                    <span> 个人中心</span>");
document.writeln("                </a>");
document.writeln("");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>");
document.writeln("                    <i class=\'iconfont icon-weihu\'></i>");
document.writeln("                    <span> 售后服务</span>");
document.writeln("                </a>");
document.writeln("");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>");
document.writeln("                    <i class=\'iconfont icon-kefu\'></i>");
document.writeln("                    <span> 人工服务</span>");
document.writeln("                </a>");
document.writeln("");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("");
document.writeln("                <a href=\'#\'>");
document.writeln("                    <i class=\'iconfont icon-gouwuche\'></i>");
document.writeln("                    <span> 购物车</span>");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("    <div class=\'goTop\'>");
document.writeln("        <ul>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>");
document.writeln("                    <i class=\'iconfont icon-dingbu\'></i>");
document.writeln("                    <span>回顶部</span>");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("    <!-- 侧边栏区域结束 -->");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");